newsapp/urls.py
from django.urls import path, include, re_path
from .views import *

urlpatterns= [
    path('', index, name='home'),
    path('contact', contact, name='contact'),
    path('menu-content/<slug>', menu_content, name='menu-content'),
    path('test-page', test_page, name='test-page'),
    path('details/<slug>', details, name='details'),
    path('horoscope-detail/<param>', horoscope_detail, name='horoscope-detail'),
    path('slider-detail/<slug>', slider_detail, name='slider-detail'),
    path('sponsors', sponsors, name='sponsors'),
]

newsportal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('newsapp.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "NewsGram"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "NewsGram"

newsapp/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField, RichTextFormField
from ckeditor_uploader.fields import RichTextUploadingField # to activate upload option in ckeditor for uploading files to the server
from django.utils.safestring import mark_safe
from django.template.defaultfilters import truncatechars, truncatewords  # to slice words or characters from string in admin table
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils.text import slugify 
# Create your models here.

class Menu(models.Model):
    """This model is for creating dynamic menus.
    """
    
    is_main_menu_choices = (
        ('y', 'Yes'),
        ('n', 'No'),
    )
    is_main_menu = models.CharField(max_length=10, choices=is_main_menu_choices)
    menu_name = models.CharField(max_length = 100)
    slug = models.SlugField(max_length = 150, default = None, unique=True)
    parent_menu = models.ForeignKey('self', on_delete=models.CASCADE, limit_choices_to={'is_main_menu': 'y'}, blank=True, null=True)
    # sub_menu_name = models.CharField(max_length = 100, blank=True, null=True)
    page_type_choices = (
        ('dp', 'Detail Page'),
        ('slp', 'Simple Listing Page'),
        ('tlp', 'Thumbnail Listing Page'),
        ('clp', 'Collapsible Listing Page'),
        ('gp', 'Gallery Page'),
    )
    page_type = models.CharField(max_length=10, choices=page_type_choices)
    order_by = models.IntegerField()
    status = models.BooleanField(default=True, max_length=5)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    # updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.menu_name
    
    def clean(self):
        """
        Validate custom constraints. Here, this method determines that if the 'is_main_menu' = 'n', then the field 'parent_menu' is required.
        """
        # if self.is_main_menu == 'n' and self.parent_menu is None and self.sub_menu_name is None:
        if self.is_main_menu == 'n' and self.parent_menu is None:
            raise ValidationError({
                'parent_menu': _('This field is required.'),
                # 'sub_menu_name': _('This field is required.')
            })
            
    class Meta:
        verbose_name_plural = "Menu" # Renames the model to Menu
        
    def save(self, *args, **kwargs):
        """This allows changes in slug while editing.
        """
        self.slug = slugify(self.menu_name)
        return super(Menu, self).save(*args, **kwargs)
            
            
class MenuContent(models.Model):
    """This model is for maintaining contents of menu.
    """
    
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    title = models.CharField(max_length = 255)
    slug = models.SlugField(max_length = 255, unique=True)
    description = RichTextUploadingField(blank=True, null=True)
    image = models.ImageField(max_length = 255, upload_to = 'images/menu/', blank=True, null=True, verbose_name="Thumbnail Image")
    files = models.FileField(max_length = 255, upload_to = 'files/menu/', blank=True, null=True)
    status = models.BooleanField(default=True, max_length=5)
    visited = models.IntegerField(default=0, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name='menucontent_created_by')
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    # updated_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='menucontent_updated_by')
    # updated_at = models.DateTimeField(auto_now=True)
   
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Menu Contents" # Renames the model to Menu Contents
        
    def get_image(self):
        """This method displays the image thumbnail instead of image path in the list display of admin section.
        """
        return mark_safe("<img src='/media/%s' width=70>" % self.image)
    get_image.short_description = 'Images' # Renames the above declared Get Image to Images.
        
    def get_file(self):
        """This method displays 'Show File' instead of file path in the list display of admin section.
        """
        return mark_safe("<a href='/media/%s' target='_blank'>Show File</a>" % self.files)
    get_file.short_description = 'Files' # Renames the above declared Get File to Files.
    
    def get_description(self):
        """This method limits the words to 50 in the description field in the list.
        """
        return truncatewords(self.description, 50)
    get_description.short_description = 'Description' # Renames the above declared Get Description to Description.
    
    def save(self, *args, **kwargs):
        """This allows changes in slug while editing.
        """
        self.slug = slugify(self.title)
        return super(MenuContent, self).save(*args, **kwargs)
    
    
# @receiver(post_delete, sender = MenuContent) # NO required now
# def del_menucontent_img(sender, instance, **kwargs):
#     """ After the object/data is deleted, the image is unlinked fron the path through this function.
    
#     Arguments:
#         sender {string} -- Name of the model.
#         instance {string} -- [description]
#     """
#     instance.image.delete(False) 
    
    
class ImageSlider(models.Model):
    """This model is for maintaining contents of image slider.
    """
    
    image = models.ImageField(max_length=255, upload_to='images/slider')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length = 255, unique=True)
    description = RichTextUploadingField(blank=True, null=True)
    order_by = models.IntegerField(default=0)
    status = models.BooleanField(default=True, max_length=5)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name='imgslider_created_by')
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
 
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Image Slider" # Renames the model to Menu Contents
        
    def get_image(self):
        """This method displays the image thumbnail instead of image path in the list display of admin section.
        """
        return mark_safe("<img src='/media/%s' width=70>" % self.image)
    get_image.short_description = 'Image' # Renames the above declared Get Image to Images.
    
    def get_description(self):
        """This method limits the words to 50 in the description field in the list.
        """
        return truncatewords(self.description, 25)
    get_description.short_description = 'Description' # Renames the above declared Get Description to Description
    
    def save(self, *args, **kwargs):
        """This allows changes in slug while editing.
        """
        self.slug = slugify(self.title)
        return super(ImageSlider, self).save(*args, **kwargs)
    

class QuickLinks(models.Model):
    """This model is for maintaining quicklinks as implemented on the footer of the site.
    """
    
    title = models.CharField(max_length=100)
    link = models.CharField(max_length=200)
    order_by = models.IntegerField()
    status = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name='quicklinks_created_by')
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Quick Links" # Renames the model to Menu Contents
        
    def get_link(self):
        """This method displays 'Go to Links' instead of showing links directly in the list display of admin section.
        """
        return mark_safe("<a href='%s' target='_blank'>Go to Link</a>" % self.link)
    get_link.short_description = 'Links' # Renames the above declared Get File to Files.
    
    
class SocialLinks(models.Model):
    """This model is for maintaining quicklinks as implemented on the footer of the site.
    """
    
    social_site_choices = (
        ('facebook', 'Facebook'),
        ('twitter', 'Twitter'),
        ('flickr', 'Flickr'),
        ('pinterest', 'Pinterest'),
        ('googleplus', 'Google Plus'),
        ('vimeo', 'Vimeo'),
        ('youtube', 'Youtube'),
        ('gmail', 'Gmail'),
    )
    social_site = models.CharField(max_length=20, choices=social_site_choices, unique=True)
    link = models.CharField(max_length=200)
    order_by = models.IntegerField()
    status = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name='socialinks_created_by')
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    
    def __str__(self):
        return self.social_site
    
    class Meta:
        verbose_name_plural = "Social Links" # Renames the model to Menu Contents
        
    def get_link(self):
        """This method displays 'Go to Links' instead of showing links directly in the list display of admin section.
        """
        return mark_safe("<a href='%s' target='_blank'>Go to Link</a>" % self.link)
    get_link.short_description = 'Links' # Renames the above declared Get File to Files.
    

class Horoscope(models.Model):
    """This model is for maintaining the horoscopre inital contents.
    """
    
    name = models.CharField(max_length=200)
    dates = models.CharField(max_length=200)
    image = models.ImageField(max_length = 255, upload_to = 'images/horoscope/', blank=True, null=True)
    order_by = models.IntegerField()
    status = models.BooleanField(default=False)
    
    def __str__(self):

newsapp/templates/layouts/footer.html
{% load static %}

	<footer id="footer">
		<div class="footer_top">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-4">
					<div class="footer_widget wow fadeInLeftBig">
						<h2>Know Us More</h2>
						{% for about in about_us %}
							{{about.description|safe|truncatewords:50}}
						{% endfor %}
						<a href="{% url 'menu-content' 'about' %}" class="about_read_more">Read More <span class="fa fa-arrow-right right_arrow"></span></a> 

						<div class="fb-like" data-href="https://www.facebook.com/developerstage/" data-width="" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

						<div style="margin: 5px 0 0 0"><a class="twitter-follow-button"
							href="https://twitter.com/TwitterDev">
						  Follow @TwitterDev</a></div>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4">
					<div class="footer_widget wow fadeInDown">
						<h2>Quick Links</h2>
						<ul class="tag_nav">
							{% if quicklinks_data %}
								{% for quicklink in quicklinks_data %}
									<li><a href="{{quicklink.link}}" target="_blank">{{quicklink.title}}</a></li>
								{% endfor %}
							{% endif %}
						</ul>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4">
					<div class="footer_widget wow fadeInRightBig">
						<h2>Contact</h2>
						{% for contact in contact_info %}
							{{contact.description|safe}}
						{% endfor %}

						<h2>News Letter</h2>
						<div class="email-box">
							<input type="text" class="subscribe_email" placeholder="Enter your email..." />
							<button type="submit" class="subscribe_btn">Subscribe</button>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer_bottom">
			<div class="col-md-4"><p class="copyright">Copyright &copy; {% now 'Y' %} <a href="{% url 'home' %}">NewsGram</a></p></div>

			<div class="col-md-4" align='center'>Site Visit <img src='http://www.hit-counts.com/counter.php?t=MTQ0MTgzNA==' border='0' alt='hit counter'><BR><a href='https://www.glowgraphics.co.uk/'>professional logo</a></div>

			<div class="col-md-4"><p class="developer" style="color: #c6c6c6">Developed By <a href="https://www.linkedin.com/in/ujjwal-shrestha-april17/" target="_blank" style="color: white" class="developer_name">UjjwalShrestha</a></p></div>
		</div>
	</footer>

</div>

<!--Start of Tawk.to Script-->
<script type="text/javascript">
	var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
	(function(){
	var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
	s1.async=true;
	s1.src='https://embed.tawk.to/5d676918eb1a6b0be609e9e4/default';
	s1.charset='UTF-8';
	s1.setAttribute('crossorigin','*');
	s0.parentNode.insertBefore(s1,s0);
	})();
</script>
<!--End of Tawk.to Script-->



</body>
</html>

newsapp/templates/layouts/header.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    {% for title in site_title %}
        <title>{{title.name}} {% if tab_title %}| {{tab_title}} {% endif %}</title>
    {% endfor %}
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/li-scroller.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/overlaypopup.css' %}">

    {% for icon in site_icon %}
        <link rel="icon" href="{{icon.image.url}}">
    {% endfor %}
    <!--[if lt IE 9]>
    <script src="assets/js/html5shiv.min.js"></script>
    <script src="assets/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    
<div id="preloader">
    <div id="status">&nbsp;</div>
</div>

<a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>

<div class="container-fluid">

newsapp/templates/layouts/nav.html
{% load static %}

<section id="navArea">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav main_nav">
                <!-- Default home menu -->
                <li class="active"><a href="{% url 'home' %}"><span class="fa fa-home desktop-home"></span><span class="mobile-show">Home</span></a></li>
                
                <!-- Checking if menu data exists  -->
                {% if menu_data %}

                    <!-- All menu loop -->
                    {% for menu in menu_data %}

                        <!-- Checking if the menu has submenu -->
                        {% if menu.menu_set.all %} 

                            <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{menu.menu_name}}</a>
                                
                                {% if menu.menu_set.all %}
                                    <ul class="dropdown-menu" role="menu">
                                        <!-- Sub menu loop -->
                                        {% for submenu in menu.menu_set.all %}
                                            {% if submenu.status == True %}
                                                <li><a href="{% url 'menu-content' submenu.slug %}">{{submenu.menu_name}}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                {% endif %}

                            </li> 

                        <!-- Else checking if the menu is main menu (not submenu) -->
                        {% elif menu.is_main_menu == 'y' %}

                            <li><a href="{% url 'menu-content' menu.slug %}">{{menu.menu_name}}</a></li>

                        {% endif %}

                    {% endfor %}

                {% endif %}
                
            </ul>
        </div>
    </nav>
</section>

<section id="newsSection">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="latest_newsarea"> <span>Latest News</span>
                <ul id="ticker01" class="news_sticker">
                    {% if latest_news %}
                        {% for news in latest_news %}
                            <li><a href="{% url 'details' news.slug %}"><i class="fa fa-angle-double-right" style="font-size: 12px"></i> {{news.title}}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
                <div class="social_area">
                    <ul class="social_nav">
                        {% if sociallinks_data %}
                            {% for social_link in sociallinks_data %}
                                <li class="{{social_link.social_site}}"><a href="{{social_link.link}}" target="_blank"></a></li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

newsapp/templates/layouts/nav_bkup.html
{% load static %}

<section id="navArea">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav main_nav">
                <!-- Default home menu -->
                <li class="active"><a href="{% url 'home' %}"><span class="fa fa-home desktop-home"></span><span class="mobile-show">Home</span></a></li>
                
                <!-- Checking if menu data exists  -->
                {% if menu_data %}

                    <!-- All menu loop -->
                    {% for menu in menu_data %}

                        <!-- Checking if the menu has submenu -->
                        {% if menu.menu_set.all %} 

                            <!-- Sub menu loop -->
                            {% for submenu in menu.menu_set.all %}

                                <!-- Check if status of submenu is true -->
                                {% if submenu.status == True %}
                                    <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{menu.menu_name}}</a>
                                        
                                        <ul class="dropdown-menu" role="menu">
                                            <!-- Sub menu -->
                                            <li><a href="{% url 'menu-content' submenu.slug %}">{{submenu.menu_name}}</a></li>
                                        </ul>

                                    </li> 
                                
                                <!-- If status of submenu is not true -->
                                {% else %}
                                    <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{menu.menu_name}}</a></li> 
                                {% endif %}
                                
                            {% endfor %}

                        <!-- Else checking if the menu is main menu (not submenu) -->
                        {% elif menu.is_main_menu == 'y' %}

                            <li><a href="{% url 'menu-content' menu.slug %}">{{menu.menu_name}}</a></li>

                        {% endif %}

                    {% endfor %}

                {% endif %}
                
            </ul>
        </div>
    </nav>
</section>

<section id="newsSection">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="latest_newsarea"> <span>Latest News</span>
                <ul id="ticker01" class="news_sticker">
                    <li><a href="#"><img src="{% static 'images/news_thumbnail3.jpg' %}" alt="">My First News Item</a></li>
                    <li><a href="#"><img src="{% static 'images/news_thumbnail3.jpg' %}" alt="">My Second News Item</a></li>
                    <li><a href="#"><img src="{% static 'images/news_thumbnail3.jpg' %}" alt="">My Third News Item</a></li>
                    <li><a href="#"><img src="{% static 'images/news_thumbnail3.jpg' %}" alt="">My Four News Item</a></li>
                    <li><a href="#"><img src="{% static 'images/news_thumbnail3.jpg' %}" alt="">My Five News Item</a></li>
                    <li><a href="#"><img src="{% static 'images/news_thumbnail3.jpg' %}" alt="">My Six News Item</a></li>
                    <li><a href="#"><img src="{% static 'images/news_thumbnail3.jpg' %}" alt="">My Seven News Item</a></li>
                    <li><a href="#"><img src="{% static 'images/news_thumbnail3.jpg' %}" alt="">My Eight News Item</a></li>
                    <li><a href="#"><img src="{% static 'images/news_thumbnail2.jpg' %}" alt="">My Nine News Item</a></li>
                </ul>
                <div class="social_area">
                    <ul class="social_nav">
                        <li class="facebook"><a href="#"></a></li>
                        <li class="twitter"><a href="#"></a></li>
                        <li class="flickr"><a href="#"></a></li>
                        <li class="pinterest"><a href="#"></a></li>
                        <li class="googleplus"><a href="#"></a></li>
                        <li class="vimeo"><a href="#"></a></li>
                        <li class="youtube"><a href="#"></a></li>
                        <li class="mail"><a href="#"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

newsapp/templates/layouts/script.html
{% load static %}

<!-- recaptcha js -->
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script src="{% static 'js/jquery.min.js' %}"></script> 
<script src="{% static 'js/wow.min.js' %}"></script> 
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<script src="{% static 'js/slick.min.js' %}"></script> 
<script src="{% static 'js/jquery.li-scroller.1.0.js' %}"></script> 
<script src="{% static 'js/jquery.newsTicker.min.js' %}"></script> 
<script src="{% static 'js/jquery.fancybox.pack.js' %}"></script> 
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/overlay.js' %}"></script>

<script type="text/javascript">
    //-------------------------------- Scripts For Timer in dashboard Top-Nav ----------------------------------//

    tday=new Array("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday");
    tmonth=new Array("January","February","March","April","May","June","July","August","September","October","November","December");

    function GetClock(){
        var d=new Date();
        var nday=d.getDay(), nmonth=d.getMonth(),ndate=d.getDate(),nyear=d.getYear(),nhour=d.getHours(),nmin=d.getMinutes(),nsec=d.getSeconds(),ap;

        if(nhour==0){ap=" AM";nhour=12;}
        else if(nhour<12){ap=" AM";}
        else if(nhour==12){ap=" PM";}
        else if(nhour>12){ap=" PM";nhour-=12;}

        if(nyear<1000) nyear+=1900;
        if(nmin<=9) nmin="0"+nmin;
        if(nsec<=9) nsec="0"+nsec;

        document.getElementById('clockbox').innerHTML=""+tday[nday]+", "+tmonth[nmonth]+" "+ndate+", "+nyear+" "+nhour+":"+nmin+":"+nsec+ap+"";
    }

    window.onload=function(){
        GetClock();
        setInterval(GetClock,1000);
    }

    //---------------------------- Scripts For Timer in dashboard Top-Nav Ends here ------------------------------//


    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });


    $(document).ready(function() {
        $(".alert-success").fadeTo(5000, 500).slideUp(500, function(){
            $(".alert-success").slideUp(500);
        });

        $(".alert-danger").fadeTo(5000, 500).slideUp(500, function(){
            $(".alert-danger").slideUp(500);
        });

        $(".alert-info").fadeTo(5000, 500).slideUp(500, function(){
            $(".alert-info").slideUp(500);
        });

        $(".alert-warning").fadeTo(5000, 500).slideUp(500, function(){
            $(".alert-warning").slideUp(500);
        });
    });

    
</script>

<!-- Like and share button js script -->
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v4.0"></script>


<!-- Facebook page plugin: Developer's Stage -->
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v4.0"></script>


<!-- Twitter developers mode script -->
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

newsapp/templates/layouts/top-head.html
{% load static %}

<header id="header">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="header_top">
                <div class="header_top_left">
                    <ul class="top_nav">
                        <li><a href="#">Create Account</a></li>
                        <li><a href="#">Login</a></li>
                    </ul>
                </div>
                <div class="header_top_right">
                    <p id="clockbox"></p>
                </div>
            </div>
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="header_bottom">
                {% for logo in site_logo %}
                    <div class="logo_area"><a href="{% url 'home' %}" class="logo"><img src="{{logo.image.url}} " alt=""></a></div>
                {% endfor %}

                {% for banner in ad_banner %}
                    <div class="add_banner"><a href="{{banner.link}}" target="_blank"><img src="{{banner.image.url}}" alt=""></a></div>
                {% endfor %}
            </div>
        </div>
    </div>
</header>